window.esdocSearchIndex = [
  [
    "",
    "test-file/specs/redis-spec.js.html#lineNumber17",
    "Adapters",
    "test"
  ],
  [
    "",
    "test-file/specs/redis-spec.js.html#lineNumber19",
    "Adapters redis",
    "test"
  ],
  [
    "",
    "test-file/specs/redis-spec.js.html#lineNumber32",
    "Adapters redis should be defined",
    "test"
  ],
  [
    "",
    "test-file/specs/redis-spec.js.html#lineNumber27",
    "Adapters redis should be have mock client",
    "test"
  ],
  [
    "",
    "test-file/specs/redis-spec.js.html#lineNumber58",
    "Adapters redis should get all docs",
    "test"
  ],
  [
    "",
    "test-file/specs/redis-spec.js.html#lineNumber44",
    "Adapters redis should get object",
    "test"
  ],
  [
    "",
    "test-file/specs/redis-spec.js.html#lineNumber51",
    "Adapters redis should remove object",
    "test"
  ],
  [
    "",
    "test-file/specs/redis-spec.js.html#lineNumber37",
    "Adapters redis should save object",
    "test"
  ],
  [
    "",
    "test-file/specs/admin-controller-spec.js.html#lineNumber35",
    "Admin",
    "test"
  ],
  [
    "",
    "test-file/specs/admin-controller-spec.js.html#lineNumber48",
    "Admin Admin Controller",
    "test"
  ],
  [
    "",
    "test-file/specs/admin-controller-spec.js.html#lineNumber64",
    "Admin Admin Controller get_downloadPass - Handles download pass request",
    "test"
  ],
  [
    "",
    "test-file/specs/admin-controller-spec.js.html#lineNumber72",
    "Admin Admin Controller get_find - Handles finding a pass",
    "test"
  ],
  [
    "",
    "test-file/specs/admin-controller-spec.js.html#lineNumber68",
    "Admin Admin Controller get_signPass - Handles signing a pass",
    "test"
  ],
  [
    "",
    "test-file/specs/admin-controller-spec.js.html#lineNumber60",
    "Admin Admin Controller post_passTypeIdentifier - Handles creating passTypeIdentifier",
    "test"
  ],
  [
    "",
    "test-file/specs/admin-controller-spec.js.html#lineNumber52",
    "Admin Admin Controller should be defined",
    "test"
  ],
  [
    "",
    "test-file/specs/admin-controller-spec.js.html#lineNumber56",
    "Admin Admin Controller should return instance",
    "test"
  ],
  [
    "",
    "test-file/specs/admin-controller-spec.js.html#lineNumber78",
    "Admin Admin Routes",
    "test"
  ],
  [
    "",
    "test-file/specs/admin-controller-spec.js.html#lineNumber161",
    "Admin Admin Routes Downloading",
    "test"
  ],
  [
    "",
    "test-file/specs/admin-controller-spec.js.html#lineNumber162",
    "Admin Admin Routes Downloading ",
    "test"
  ],
  [
    "",
    "test-file/specs/admin-controller-spec.js.html#lineNumber168",
    "Admin Admin Routes Downloading ",
    "test"
  ],
  [
    "",
    "test-file/specs/admin-controller-spec.js.html#lineNumber129",
    "Admin Admin Routes Finding",
    "test"
  ],
  [
    "",
    "test-file/specs/admin-controller-spec.js.html#lineNumber131",
    "Admin Admin Routes Finding GET - /api/v1/admin/find?docType=device - should return documents matching.",
    "test"
  ],
  [
    "",
    "test-file/specs/admin-controller-spec.js.html#lineNumber138",
    "Admin Admin Routes Finding GET - /api/v1/admin/find?name=value - should return 404 if no match",
    "test"
  ],
  [
    "",
    "test-file/specs/admin-controller-spec.js.html#lineNumber79",
    "Admin Admin Routes Identifiers",
    "test"
  ],
  [
    "",
    "test-file/specs/admin-controller-spec.js.html#lineNumber80",
    "Admin Admin Routes Identifiers /api/v1/admin/identifiers - should create new pass type identifier entry",
    "test"
  ],
  [
    "",
    "test-file/specs/admin-controller-spec.js.html#lineNumber89",
    "Admin Admin Routes Identifiers /api/v1/admin/identifiers - should get pass type identifier",
    "test"
  ],
  [
    "",
    "test-file/specs/admin-controller-spec.js.html#lineNumber96",
    "Admin Admin Routes Identifiers /api/v1/admin/identifiers - should not get pass type identifier",
    "test"
  ],
  [
    "",
    "test-file/specs/admin-controller-spec.js.html#lineNumber104",
    "Admin Admin Routes Passes",
    "test"
  ],
  [
    "",
    "test-file/specs/admin-controller-spec.js.html#lineNumber121",
    "Admin Admin Routes Passes GET - /api/v1/admin/passes/:id - should return 1 pass",
    "test"
  ],
  [
    "",
    "test-file/specs/admin-controller-spec.js.html#lineNumber105",
    "Admin Admin Routes Passes POST - /api/v1/admin/passes - should create pass",
    "test"
  ],
  [
    "",
    "test-file/specs/admin-controller-spec.js.html#lineNumber114",
    "Admin Admin Routes Passes PUT - /api/v1/admin/passes/:ID - should update pass",
    "test"
  ],
  [
    "",
    "test-file/specs/admin-controller-spec.js.html#lineNumber147",
    "Admin Admin Routes Signing",
    "test"
  ],
  [
    "",
    "test-file/specs/admin-controller-spec.js.html#lineNumber148",
    "Admin Admin Routes Signing ",
    "test"
  ],
  [
    "",
    "test-file/specs/admin-controller-spec.js.html#lineNumber154",
    "Admin Admin Routes Signing ",
    "test"
  ],
  [
    "",
    "test-file/specs/auth-controller-spec.js.html#lineNumber14",
    "Auth",
    "test"
  ],
  [
    "",
    "test-file/specs/auth-controller-spec.js.html#lineNumber61",
    "Auth Account",
    "test"
  ],
  [
    "",
    "test-file/specs/auth-controller-spec.js.html#lineNumber63",
    "Auth Account GET - /account - should return account view",
    "test"
  ],
  [
    "",
    "test-file/specs/auth-controller-spec.js.html#lineNumber71",
    "Auth Account GET - /me - should return json user info",
    "test"
  ],
  [
    "",
    "test-file/specs/auth-controller-spec.js.html#lineNumber111",
    "Auth Auth Controller",
    "test"
  ],
  [
    "",
    "test-file/specs/auth-controller-spec.js.html#lineNumber116",
    "Auth Auth Controller should be defined",
    "test"
  ],
  [
    "",
    "test-file/specs/auth-controller-spec.js.html#lineNumber121",
    "Auth Auth Controller should create instance",
    "test"
  ],
  [
    "",
    "test-file/specs/auth-controller-spec.js.html#lineNumber81",
    "Auth Authorization",
    "test"
  ],
  [
    "",
    "test-file/specs/auth-controller-spec.js.html#lineNumber83",
    "Auth Authorization GET - /login - should return login form",
    "test"
  ],
  [
    "",
    "test-file/specs/auth-controller-spec.js.html#lineNumber101",
    "Auth Authorization GET - /logout - should return logout",
    "test"
  ],
  [
    "",
    "test-file/specs/auth-controller-spec.js.html#lineNumber90",
    "Auth Authorization POST - /login - should login user",
    "test"
  ],
  [
    "",
    "test-file/specs/auth-controller-spec.js.html#lineNumber18",
    "Auth GET - /index - should return index",
    "test"
  ],
  [
    "",
    "test-file/specs/auth-controller-spec.js.html#lineNumber25",
    "Auth Register",
    "test"
  ],
  [
    "",
    "test-file/specs/auth-controller-spec.js.html#lineNumber53",
    "Auth Register GET - /signup - should return register form",
    "test"
  ],
  [
    "",
    "test-file/specs/auth-controller-spec.js.html#lineNumber40",
    "Auth Register POST - /signup - should register new user",
    "test"
  ],
  [
    "",
    "test-file/specs/auth-controller-spec.js.html#lineNumber27",
    "Auth Register POST - /signup - should register user",
    "test"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "",
    "test-file/specs/couchdb-spec.js.html#lineNumber90",
    "CouchDB Adapter",
    "test"
  ],
  [
    "",
    "test-file/specs/couchdb-spec.js.html#lineNumber192",
    "CouchDB Adapter db.allDocs - should return array of docs",
    "test"
  ],
  [
    "",
    "test-file/specs/couchdb-spec.js.html#lineNumber108",
    "CouchDB Adapter db.put - should create doc with id",
    "test"
  ],
  [
    "",
    "test-file/specs/couchdb-spec.js.html#lineNumber119",
    "CouchDB Adapter db.put - should reject create doc with _id",
    "test"
  ],
  [
    "",
    "test-file/specs/couchdb-spec.js.html#lineNumber92",
    "CouchDB Adapter should be defined",
    "test"
  ],
  [
    "",
    "test-file/specs/couchdb-spec.js.html#lineNumber97",
    "CouchDB Adapter should have allDocs, get, remove, put methods",
    "test"
  ],
  [
    "",
    "test-file/specs/db-controller-spec.js.html#lineNumber33",
    "DB",
    "test"
  ],
  [
    "",
    "test-file/specs/db-controller-spec.js.html#lineNumber35",
    "DB DB Controller",
    "test"
  ],
  [
    "",
    "test-file/specs/db-controller-spec.js.html#lineNumber40",
    "DB DB Controller should be defined",
    "test"
  ],
  [
    "",
    "test-file/specs/db-controller-spec.js.html#lineNumber45",
    "DB DB Controller should create instance",
    "test"
  ],
  [
    "",
    "test-file/specs/db-controller-spec.js.html#lineNumber51",
    "DB DB Routes",
    "test"
  ],
  [
    "",
    "test-file/specs/db-controller-spec.js.html#lineNumber92",
    "DB DB Routes DELETE - /api/v1/db - should remove doc",
    "test"
  ],
  [
    "",
    "test-file/specs/db-controller-spec.js.html#lineNumber53",
    "DB DB Routes GET - /api/v1/db - should return all docs",
    "test"
  ],
  [
    "",
    "test-file/specs/db-controller-spec.js.html#lineNumber80",
    "DB DB Routes GET - /api/v1/db/:id - should get doc",
    "test"
  ],
  [
    "",
    "test-file/specs/db-controller-spec.js.html#lineNumber60",
    "DB DB Routes POST - /api/v1/db - should create doc",
    "test"
  ],
  [
    "",
    "test-file/specs/db-controller-spec.js.html#lineNumber71",
    "DB DB Routes PUT - /api/v1/db - should update doc and return 200",
    "test"
  ],
  [
    "",
    "test-file/specs/device-spec.js.html#lineNumber11",
    "Device Model",
    "test"
  ],
  [
    "",
    "test-file/specs/device-spec.js.html#lineNumber21",
    "Device Model should be defined",
    "test"
  ],
  [
    "",
    "test-file/specs/pass-model-spec.js.html#lineNumber9",
    "Pass",
    "test"
  ],
  [
    "",
    "test-file/specs/pass-model-spec.js.html#lineNumber10",
    "Pass should create default generic Pass",
    "test"
  ],
  [
    "",
    "test-file/specs/pass-model-spec.js.html#lineNumber18",
    "Pass should create pass model with [storeCard] type",
    "test"
  ],
  [
    "",
    "test-file/specs/pass-model-spec.js.html#lineNumber27",
    "Pass should create pass model with teamIdentifier, passTypeIdentifier, and webServiceURL from config",
    "test"
  ],
  [
    "",
    "test-file/specs/models-spec.js.html#lineNumber9",
    "Passes",
    "test"
  ],
  [
    "",
    "test-file/specs/passes-model-spec.js.html#lineNumber13",
    "Passes",
    "test"
  ],
  [
    "",
    "test-file/specs/passes-model-spec.js.html#lineNumber29",
    "Passes add() - should add pass",
    "test"
  ],
  [
    "",
    "test-file/specs/passes-model-spec.js.html#lineNumber65",
    "Passes find(params) - should reject promise pass that meets params",
    "test"
  ],
  [
    "",
    "test-file/specs/passes-model-spec.js.html#lineNumber50",
    "Passes find(params) - should resolve pass that meets params",
    "test"
  ],
  [
    "",
    "test-file/specs/passes-model-spec.js.html#lineNumber78",
    "Passes findBySerial(num) - should return pass by serial number",
    "test"
  ],
  [
    "",
    "test-file/specs/passes-model-spec.js.html#lineNumber39",
    "Passes get() - should get pass",
    "test"
  ],
  [
    "",
    "test-file/specs/passes-model-spec.js.html#lineNumber19",
    "Passes getPasses() - should return all passes",
    "test"
  ],
  [
    "",
    "test-file/specs/passes-model-spec.js.html#lineNumber88",
    "Passes remove() - should remove pass",
    "test"
  ],
  [
    "",
    "test-file/specs/passes-model-spec.js.html#lineNumber14",
    "Passes should be defined",
    "test"
  ],
  [
    "",
    "test-file/specs/models-spec.js.html#lineNumber10",
    "Passes should return only passes",
    "test"
  ],
  [
    "",
    "test-file/specs/signpass-spec.js.html#lineNumber19",
    "SignPass",
    "test"
  ],
  [
    "",
    "test-file/specs/signpass-spec.js.html#lineNumber34",
    "SignPass Certs",
    "test"
  ],
  [
    "",
    "test-file/specs/signpass-spec.js.html#lineNumber42",
    "SignPass Certs createPems() - should create -cert.pem and -key.pem files from a .p12 certficate.",
    "test"
  ],
  [
    "",
    "test-file/specs/signpass-spec.js.html#lineNumber63",
    "SignPass Certs should be fetch pass type info",
    "test"
  ],
  [
    "",
    "test-file/specs/signpass-spec.js.html#lineNumber36",
    "SignPass Certs should return PassTypeId object",
    "test"
  ],
  [
    "",
    "test-file/specs/signpass-spec.js.html#lineNumber81",
    "SignPass Siging",
    "test"
  ],
  [
    "",
    "test-file/specs/signpass-spec.js.html#lineNumber109",
    "SignPass Siging Batching",
    "test"
  ],
  [
    "",
    "test-file/specs/signpass-spec.js.html#lineNumber126",
    "SignPass Siging Batching sign() - all passes - should create .zip and .pkpass for each pass type",
    "test"
  ],
  [
    "",
    "test-file/specs/signpass-spec.js.html#lineNumber92",
    "SignPass Siging sign() - should create .zip and .pkpass files",
    "test"
  ],
  [
    "",
    "test-file/specs/signpass-spec.js.html#lineNumber23",
    "SignPass should be defined",
    "test"
  ],
  [
    "",
    "test-file/specs/user-spec.js.html#lineNumber11",
    "User Model",
    "test"
  ],
  [
    "",
    "test-file/specs/user-spec.js.html#lineNumber23",
    "User Model should be defined",
    "test"
  ],
  [
    "",
    "test-file/specs/user-spec.js.html#lineNumber28",
    "User Model should create instance",
    "test"
  ],
  [
    "",
    "test-file/specs/user-spec.js.html#lineNumber34",
    "User Model should not have _json",
    "test"
  ],
  [
    "",
    "test-file/specs/user-spec.js.html#lineNumber41",
    "User Model should not have _raw",
    "test"
  ],
  [
    "",
    "test-file/specs/users-spec.js.html#lineNumber31",
    "Users Model",
    "test"
  ],
  [
    "",
    "test-file/specs/users-spec.js.html#lineNumber42",
    "Users Model be defined",
    "test"
  ],
  [
    "",
    "test-file/specs/users-spec.js.html#lineNumber46",
    "Users Model create(user, done) - should create a user",
    "test"
  ],
  [
    "",
    "test-file/specs/users-spec.js.html#lineNumber102",
    "Users Model find(profile, done) - should find user unsuccessfully",
    "test"
  ],
  [
    "",
    "test-file/specs/users-spec.js.html#lineNumber127",
    "Users Model findByUsername(profile, done) - should find user successfully",
    "test"
  ],
  [
    "",
    "test-file/specs/users-spec.js.html#lineNumber79",
    "Users Model findOrCreate(profile, done) - should find/create user successfully",
    "test"
  ],
  [
    "",
    "test-file/specs/users-spec.js.html#lineNumber91",
    "Users Model findOrCreate(profile, done) - should find/create user successfully",
    "test"
  ],
  [
    "",
    "test-file/specs/users-spec.js.html#lineNumber57",
    "Users Model getUsers() - should fetch users and resolve promise on success",
    "test"
  ],
  [
    "",
    "test-file/specs/users-spec.js.html#lineNumber68",
    "Users Model save(user, done) - should create a user",
    "test"
  ],
  [
    "",
    "test-file/specs/users-spec.js.html#lineNumber116",
    "Users Model validate(user, done) - find valid user by username/password",
    "test"
  ],
  [
    "",
    "test-file/specs/jps-utils-spec.js.html#lineNumber15",
    "Utils",
    "test"
  ],
  [
    "",
    "test-file/specs/jps-utils-spec.js.html#lineNumber47",
    "Utils checksum() - should create a checksum hash",
    "test"
  ],
  [
    "",
    "test-file/specs/jps-utils-spec.js.html#lineNumber17",
    "Utils should be defined",
    "test"
  ],
  [
    "",
    "test-file/specs/db-spec.js.html#lineNumber25",
    "db",
    "test"
  ],
  [
    "",
    "test-file/specs/db-spec.js.html#lineNumber43",
    "db bulkDocs(array) - should save array of docs",
    "test"
  ],
  [
    "",
    "test-file/specs/db-spec.js.html#lineNumber108",
    "db find(params) - should find params and resolve promise",
    "test"
  ],
  [
    "",
    "test-file/specs/db-spec.js.html#lineNumber120",
    "db findBy(params) - should find object and return first match",
    "test"
  ],
  [
    "",
    "test-file/specs/db-spec.js.html#lineNumber133",
    "db findOne(params) - should find item by params and resolve promise",
    "test"
  ],
  [
    "",
    "test-file/specs/db-spec.js.html#lineNumber145",
    "db findOne(params) - should not find item by non-matching params and reject promise",
    "test"
  ],
  [
    "",
    "test-file/specs/db-spec.js.html#lineNumber79",
    "db get(id) - should get doc with id and resolve promise",
    "test"
  ],
  [
    "",
    "test-file/specs/db-spec.js.html#lineNumber65",
    "db post(obj) - should create doc with generated",
    "test"
  ],
  [
    "",
    "test-file/specs/db-spec.js.html#lineNumber54",
    "db put(obj) - should create file with id",
    "test"
  ],
  [
    "",
    "test-file/specs/db-spec.js.html#lineNumber98",
    "db remove(id) - should not remove doc with invalid id and reject promise",
    "test"
  ],
  [
    "",
    "test-file/specs/db-spec.js.html#lineNumber89",
    "db remove(id) - should remove doc with id and resolve promise",
    "test"
  ],
  [
    "",
    "test-file/specs/db-spec.js.html#lineNumber26",
    "db should be defined",
    "test"
  ],
  [
    "",
    "test-file/specs/db-spec.js.html#lineNumber31",
    "db should have allDocs, get, remove, put methods",
    "test"
  ],
  [
    "",
    "test-file/specs/jps-passbook-spec.js.html#lineNumber18",
    "jps-passbook",
    "test"
  ],
  [
    "",
    "test-file/specs/jps-passbook-spec.js.html#lineNumber19",
    "jps-passbook Batching",
    "test"
  ],
  [
    "",
    "test-file/specs/jps-passbook-spec.js.html#lineNumber27",
    "jps-passbook Batching batchPromise(\"create\", passes) - should create each pass in database",
    "test"
  ],
  [
    "",
    "test-file/specs/jps-passbook-spec.js.html#lineNumber55",
    "jps-passbook Passes",
    "test"
  ],
  [
    "",
    "test-file/specs/jps-passbook-spec.js.html#lineNumber118",
    "jps-passbook Passes Signing",
    "test"
  ],
  [
    "",
    "test-file/specs/jps-passbook-spec.js.html#lineNumber146",
    "jps-passbook Passes Signing Validation",
    "test"
  ],
  [
    "",
    "test-file/specs/jps-passbook-spec.js.html#lineNumber147",
    "jps-passbook Passes Signing Validation validatePass() - should validate a pass",
    "test"
  ],
  [
    "",
    "test-file/specs/jps-passbook-spec.js.html#lineNumber159",
    "jps-passbook Passes Signing Validation validatePassPromise() - should validate pass .pkpass signature and resolve promise",
    "test"
  ],
  [
    "",
    "test-file/specs/jps-passbook-spec.js.html#lineNumber129",
    "jps-passbook Passes Signing signPass() - should sign .raw package into a .pkpass",
    "test"
  ],
  [
    "",
    "test-file/specs/jps-passbook-spec.js.html#lineNumber139",
    "jps-passbook Passes Signing signPassPromise() - should sign pass .raw into .pkpass and resolve promise",
    "test"
  ],
  [
    "",
    "test-file/specs/jps-passbook-spec.js.html#lineNumber110",
    "jps-passbook Passes createPassPromise() - should create pass .raw and resolve promise",
    "test"
  ],
  [
    "",
    "test-file/specs/jps-passbook-spec.js.html#lineNumber103",
    "jps-passbook Passes getPassCerts() - should get pass certs from database fail.",
    "test"
  ],
  [
    "",
    "test-file/specs/jps-passbook-spec.js.html#lineNumber93",
    "jps-passbook Passes getPassCerts() - should get pass certs from database successfully.",
    "test"
  ],
  [
    "",
    "test-file/specs/jps-passbook-spec.js.html#lineNumber57",
    "jps-passbook Passes savePassTypeIdentifier() - should create pass certs and save passTypeIdentifier to database successfully.",
    "test"
  ],
  [
    "",
    "test-file/specs/jps-passbook-spec.js.html#lineNumber68",
    "jps-passbook Passes savePassTypeIdentifier() - should should fail when no p12 present.",
    "test"
  ],
  [
    "",
    "test-file/specs/jps-passbook-spec.js.html#lineNumber81",
    "jps-passbook Passes savePassTypeIdentifier() - should should fail when no passphrase present.",
    "test"
  ],
  [
    "lib/adapters/db-couchdb.js",
    "file/lib/adapters/db-couchdb.js.html",
    "lib/adapters/db-couchdb.js",
    "file"
  ],
  [
    "lib/adapters/db-redis.js",
    "file/lib/adapters/db-redis.js.html",
    "lib/adapters/db-redis.js",
    "file"
  ],
  [
    "lib/cli.js",
    "file/lib/cli.js.html",
    "lib/cli.js",
    "file"
  ],
  [
    "lib/cmds/certs.js",
    "file/lib/cmds/certs.js.html",
    "lib/cmds/certs.js",
    "file"
  ],
  [
    "lib/cmds/devices.js",
    "file/lib/cmds/devices.js.html",
    "lib/cmds/devices.js",
    "file"
  ],
  [
    "lib/cmds/passes.js",
    "file/lib/cmds/passes.js.html",
    "lib/cmds/passes.js",
    "file"
  ],
  [
    "lib/cmds/utils.js",
    "file/lib/cmds/utils.js.html",
    "lib/cmds/utils.js",
    "file"
  ],
  [
    "lib/controllers/admin-controller.js",
    "file/lib/controllers/admin-controller.js.html",
    "lib/controllers/admin-controller.js",
    "file"
  ],
  [
    "lib/controllers/app-controller.js",
    "file/lib/controllers/app-controller.js.html",
    "lib/controllers/app-controller.js",
    "file"
  ],
  [
    "lib/controllers/auth-controller.js",
    "file/lib/controllers/auth-controller.js.html",
    "lib/controllers/auth-controller.js",
    "file"
  ],
  [
    "lib/controllers/db-controller.js",
    "file/lib/controllers/db-controller.js.html",
    "lib/controllers/db-controller.js",
    "file"
  ],
  [
    "lib/controllers/devices-controller.js",
    "file/lib/controllers/devices-controller.js.html",
    "lib/controllers/devices-controller.js",
    "file"
  ],
  [
    "lib/controllers/passes-controller.js",
    "file/lib/controllers/passes-controller.js.html",
    "lib/controllers/passes-controller.js",
    "file"
  ],
  [
    "lib/db.js",
    "file/lib/db.js.html",
    "lib/db.js",
    "file"
  ],
  [
    "lib/jps-passbook.js",
    "file/lib/jps-passbook.js.html",
    "lib/jps-passbook.js",
    "file"
  ],
  [
    "lib/models/device.js",
    "file/lib/models/device.js.html",
    "lib/models/device.js",
    "file"
  ],
  [
    "lib/models/index.js",
    "file/lib/models/index.js.html",
    "lib/models/index.js",
    "file"
  ],
  [
    "lib/models/pass.js",
    "file/lib/models/pass.js.html",
    "lib/models/pass.js",
    "file"
  ],
  [
    "lib/models/passes.js",
    "file/lib/models/passes.js.html",
    "lib/models/passes.js",
    "file"
  ],
  [
    "lib/models/registration.js",
    "file/lib/models/registration.js.html",
    "lib/models/registration.js",
    "file"
  ],
  [
    "lib/models/user.js",
    "file/lib/models/user.js.html",
    "lib/models/user.js",
    "file"
  ],
  [
    "lib/models/users.js",
    "file/lib/models/users.js.html",
    "lib/models/users.js",
    "file"
  ],
  [
    "lib/program.js",
    "file/lib/program.js.html",
    "lib/program.js",
    "file"
  ],
  [
    "lib/pusher.js",
    "file/lib/pusher.js.html",
    "lib/pusher.js",
    "file"
  ],
  [
    "lib/signpass.js",
    "file/lib/signpass.js.html",
    "lib/signpass.js",
    "file"
  ],
  [
    "lib/utils.js",
    "file/lib/utils.js.html",
    "lib/utils.js",
    "file"
  ],
  [
    "",
    "test-file/specs/program-spec.js.html#lineNumber6",
    "program",
    "test"
  ],
  [
    "",
    "test-file/specs/program-spec.js.html#lineNumber7",
    "program should defined",
    "test"
  ],
  [
    "",
    "test-file/specs/program-spec.js.html#lineNumber15",
    "program should have db",
    "test"
  ],
  [
    "",
    "test-file/specs/program-spec.js.html#lineNumber11",
    "program should have getLogger",
    "test"
  ],
  [
    "",
    "test-file/specs/routes-spec.js.html#lineNumber38",
    "routes",
    "test"
  ],
  [
    "",
    "test-file/specs/routes-spec.js.html#lineNumber40",
    "routes GET - /api/v1 - should return api",
    "test"
  ],
  [
    "",
    "test-file/specs/routes-spec.js.html#lineNumber49",
    "routes PassKit Web Service",
    "test"
  ],
  [
    "",
    "test-file/specs/routes-spec.js.html#lineNumber56",
    "routes PassKit Web Service Devices",
    "test"
  ],
  [
    "",
    "test-file/specs/routes-spec.js.html#lineNumber128",
    "routes PassKit Web Service Devices DELETE - /api/v1/devices/:device_id/:pass_type_id/:serial_number - un-register device",
    "test"
  ],
  [
    "",
    "test-file/specs/routes-spec.js.html#lineNumber117",
    "routes PassKit Web Service Devices GET - /api/v1/devices/:device_id/:registrations/:pass_type_id",
    "test"
  ],
  [
    "",
    "test-file/specs/routes-spec.js.html#lineNumber90",
    "routes PassKit Web Service Devices GET - /api/v1/devices/:device_id/push/:token - send push to device",
    "test"
  ],
  [
    "",
    "test-file/specs/routes-spec.js.html#lineNumber98",
    "routes PassKit Web Service Devices GET - /api/v1/devices/:device_id/registrations/:pass_type_id - get serial numbers",
    "test"
  ],
  [
    "",
    "test-file/specs/routes-spec.js.html#lineNumber107",
    "routes PassKit Web Service Devices GET - /api/v1/devices/:device_id/registrations/:pass_type_id?passesUpdatedSince=tag - get serial numbers",
    "test"
  ],
  [
    "",
    "test-file/specs/routes-spec.js.html#lineNumber57",
    "routes PassKit Web Service Devices POST - /api/v1/devices/:device_id/registrations/:pass_type_id/:serial_number - register a new device for pass",
    "test"
  ],
  [
    "",
    "test-file/specs/routes-spec.js.html#lineNumber73",
    "routes PassKit Web Service Devices POST - /api/v1/devices/:device_id/registrations/:pass_type_id/:serial_number - return existing device for pass",
    "test"
  ],
  [
    "",
    "test-file/specs/routes-spec.js.html#lineNumber140",
    "routes PassKit Web Service Logs",
    "test"
  ],
  [
    "",
    "test-file/specs/routes-spec.js.html#lineNumber141",
    "routes PassKit Web Service Logs POST - /api/v1/log - should store logs",
    "test"
  ],
  [
    "",
    "test-file/specs/routes-spec.js.html#lineNumber152",
    "routes PassKit Web Service Passes",
    "test"
  ],
  [
    "",
    "test-file/specs/routes-spec.js.html#lineNumber160",
    "routes PassKit Web Service Passes GET - /api/v1/passes/:pass_type_id/:serial_number",
    "test"
  ],
  [
    "",
    "test-file/specs/routes-spec.js.html#lineNumber154",
    "routes PassKit Web Service Passes GET - /api/v1/passes/:pass_type_id/:serial_number - 401",
    "test"
  ],
  [
    "",
    "test-file/specs/routes-spec.js.html#lineNumber169",
    "routes PassKit Web Service Passes GET - /api/v1/passes/:pass_type_id/:serial_number - ?updated since date",
    "test"
  ],
  [
    "specs/admin-controller-spec.js",
    "test-file/specs/admin-controller-spec.js.html",
    "specs/admin-controller-spec.js",
    "testFile"
  ],
  [
    "specs/auth-controller-spec.js",
    "test-file/specs/auth-controller-spec.js.html",
    "specs/auth-controller-spec.js",
    "testFile"
  ],
  [
    "specs/couchdb-spec.js",
    "test-file/specs/couchdb-spec.js.html",
    "specs/couchdb-spec.js",
    "testFile"
  ],
  [
    "specs/db-controller-spec.js",
    "test-file/specs/db-controller-spec.js.html",
    "specs/db-controller-spec.js",
    "testFile"
  ],
  [
    "specs/db-spec.js",
    "test-file/specs/db-spec.js.html",
    "specs/db-spec.js",
    "testFile"
  ],
  [
    "specs/device-spec.js",
    "test-file/specs/device-spec.js.html",
    "specs/device-spec.js",
    "testFile"
  ],
  [
    "specs/jps-passbook-spec.js",
    "test-file/specs/jps-passbook-spec.js.html",
    "specs/jps-passbook-spec.js",
    "testFile"
  ],
  [
    "specs/jps-utils-spec.js",
    "test-file/specs/jps-utils-spec.js.html",
    "specs/jps-utils-spec.js",
    "testFile"
  ],
  [
    "specs/models-spec.js",
    "test-file/specs/models-spec.js.html",
    "specs/models-spec.js",
    "testFile"
  ],
  [
    "specs/pass-model-spec.js",
    "test-file/specs/pass-model-spec.js.html",
    "specs/pass-model-spec.js",
    "testFile"
  ],
  [
    "specs/passes-model-spec.js",
    "test-file/specs/passes-model-spec.js.html",
    "specs/passes-model-spec.js",
    "testFile"
  ],
  [
    "specs/program-spec.js",
    "test-file/specs/program-spec.js.html",
    "specs/program-spec.js",
    "testFile"
  ],
  [
    "specs/redis-spec.js",
    "test-file/specs/redis-spec.js.html",
    "specs/redis-spec.js",
    "testFile"
  ],
  [
    "specs/routes-spec.js",
    "test-file/specs/routes-spec.js.html",
    "specs/routes-spec.js",
    "testFile"
  ],
  [
    "specs/signpass-spec.js",
    "test-file/specs/signpass-spec.js.html",
    "specs/signpass-spec.js",
    "testFile"
  ],
  [
    "specs/user-spec.js",
    "test-file/specs/user-spec.js.html",
    "specs/user-spec.js",
    "testFile"
  ],
  [
    "specs/users-spec.js",
    "test-file/specs/users-spec.js.html",
    "specs/users-spec.js",
    "testFile"
  ]
]